import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F5F5F5',
        paddingHorizontal: 24,
        paddingTop: 150,
        paddingBottom: 40,
    },
    header: {
        position: 'absolute',
        top: 30,
        left: 16,
        flexDirection: 'row',
        alignItems: 'center',
    },
    logo: {
        width: 50,
        height: 50,
        marginRight: 8,
    },
    appName: {
        fontSize: 24,
        fontWeight: '700',
        color: '#024220',
    },
    heading: {
        fontSize: 22,
        fontWeight: '700',
        color: '#024220',
        textAlign: 'center',
        marginBottom: 20,
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#024220',
        borderRadius: 12,
        paddingHorizontal: 12,
        marginBottom: 12,
    },
    input: {
        flex: 1,
        paddingVertical: 10,
        paddingLeft: 10,
        color: '#024220',
    },
    link: {
        textAlign: 'right',
        color: '#024220',
        marginBottom: 20,
        fontSize: 14,
    },
    primaryButton: {
        backgroundColor: '#024220',
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: 'center',
        marginBottom: 16,
    },
    primaryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 1,
    },
    secondaryButton: {
        borderWidth: 1,
        borderColor: '#024220',
        paddingVertical: 12,
        borderRadius: 20,
        alignItems: 'center',
        marginBottom: 24,
    },
    secondaryButtonText: {
        color: '#024220',
        fontSize: 16,
        fontWeight: '600',
        letterSpacing: 1,
    },
    subText: {
        textAlign: 'center',
        color: '#024220',
        marginBottom: 8,
        fontSize: 14,
    },
    socialRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginTop: 12,
    },
    socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#024220',
        borderRadius: 20,
        paddingVertical: 8,
        paddingHorizontal: 16,
    },
    socialText: {
        marginLeft: 8,
        color: '#024220',
        fontSize: 14,
        fontWeight: '500',
    },
});